### ISSUE TITLE
database schema

### ISSUE THREAD

**Issue by ludflu** [mhollander/Expungement-Generator#1]
Hi Mike,

this is great stuff, and I'd like to contribute. I spoke with Michael Lee today about building on the expungement generator. I've checked out the code, but realized that it doesn't have the database schema anywhere that I can find. Could we do a describe on the tables and save that file so that I could get it running locally for development purposes?

Thanks,
Jim Snavely

**Comment by mhollander** [comment]
Jim -

Thank you for contacting me about this.  You bring up an excellent point.
Since I have always been working on this solo, I probably don't have things
set up in the best way.  Let me upload a schema for you right away.  Once
I'm done with that, let me know if/when you run into any other setup
issues.  I'm sure there are files here and there that I don't have uploaded
to github since I don't think about them.  One program that you will need
is pdftotext.  I believe that is not part of github since it is OSS.

Mike

**Comment by mhollander** [comment]
Also, I'd be interested in know what you intend to extend.  Perhaps we
should have a phone call to allow me to walk you through things, figure out
what you are working on, etc...

**Comment by ludflu** [comment]
great! thanks Mike. I'm not totally sure what's the most needed features are, but I'll be happy to work with you and Mike Lee to figure out what the best stuff to work on would be. For now, I'm just planning to get it up and running, and document an installation process so that it'll be simple for people (like me) to contribute.

**Comment by mhollander** [comment]
Awesome
